apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j-service
  namespace: my-restaurant
spec:
  replicas: 5
  selector:
    app: neo4j-service
  template:
    metadata:
      name: neo4j-service
      labels:
        app: neo4j-service
    spec:
      containers:
      - name: neo4j-service
        image: chrisarrefall/neo4j-service
        ports:
        - containerPort: 7474