apiVersion: v1
kind: ReplicationController
metadata:
  name: python-service
  namespace: my-restaurant
spec:
  replicas: 5
  selector:
    app: python-service
  template:
    metadata:
      name: python-service
      labels:
        app: python-service
    spec:
      containers:
      - name: python-service
        image: chrisarrefall/reports-service
        ports:
        - containerPort: 8181