apiVersion: v1
kind: ReplicationController
metadata:
  name: ruby-service
  namespace: my-restaurant
spec:
  replicas: 5
  selector:
    app: ruby-service
  template:
    metadata:
      name: ruby-service
      labels:
        app: ruby-service
    spec:
      containers:
      - name: ruby-service
        image: ochesto/ruby-service
        ports:
        - containerPort: 4567