apiVersion: v1
kind: ReplicationController
metadata:
  name: sql-service
  namespace: my-restaurant
spec:
  replicas: 2
  selector:
    app: sql-service
  template:
    metadata:
      name: sql-service
      labels:
        app: sql-service
    spec:
      containers:
      - name: sql-service
        image: chrisarrefall/sql-service
        ports:
        - containerPort: 3306